/// <reference types="node" />
import { test, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import process from 'node:process';
import { startS1Server } from '../../tests/s1/server.mjs';
import { humanAPI } from '../../tests/s1/api.mjs';
import type { components } from '../src/api/schema';

type S = components['schemas'];
test('actual project overview and human records persist across refresh and owned cold restart', async ({ page }, testInfo) => {
  test.skip(process.env.ASTROCYTE_TEST_PROJECT_BOARD !== '1', 'Requires the controller-assigned local project/browser slot.');
  test.setTimeout(600_000);
  page.setDefaultTimeout(30_000);
  const reusePath = process.env.ASTROCYTE_BOARD_REUSE_OWNED_TEMP;
  const ownedRoot = process.env.ASTROCYTE_BOARD_REUSE_APPROVED_ROOT;
  if (reusePath) expect(ownedRoot && resolve(ownedRoot) === resolve(reusePath)).toBeTruthy();
  const startupAt = Date.now();
  const server = await startS1Server({ browser: true, apiPort: 18787, webPort: 15173, ...(reusePath ? { reuseOwnedTemporary: { path: reusePath, ownedRoot: ownedRoot! } } : {}) });
  let api = await humanAPI(server.apiURL);
  let snapshot: S['RegisteredProjectSnapshotV1'];
  const read = async () => ((await api.get('/local-projects/registered')) as S['RegisteredProjectDiscoveryResultV1']).snapshot;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  let primaryError: unknown;
  console.log(JSON.stringify({ scope: 'task_live_project_board', directory: server.temporary, api: server.apiURL, web: server.webURL }));
  try {
    await expect.poll(async () => { snapshot = await read(); return snapshot.observed_at && Date.parse(snapshot.observed_at) >= startupAt && snapshot.board?.length ? snapshot.status : 'unknown'; }, { timeout: 130_000 }).toMatch(/complete|partial/);
    snapshot = await read();
    expect(snapshot.board!.length).toBeGreaterThan(0);
    await writeFile(testInfo.outputPath('actual-snapshot.json'), JSON.stringify(snapshot, null, 2));
    await page.goto(`${server.webURL}/workspace`);
    const board = page.locator('section').filter({ has: page.getByRole('heading', { name: '项目总览', exact: true }) }).first();
    await expect(board.getByLabel('项目统计')).toBeVisible();
    const active = snapshot.board!.filter(item => !item.human.archived);
    await expect(board.getByRole('button', { name: /^查看项目 / })).toHaveCount(active.length);
    const metric = (label: string) => board.getByLabel('项目统计').locator('div').filter({ has: page.locator('dt').filter({ hasText: new RegExp(`^${label}$`) }) }).locator('dd');
    await expect(metric('项目')).toHaveText(String(snapshot.board!.length));
    await expect(metric('来源文件夹')).toHaveText(String(new Set(snapshot.board!.flatMap(item => item.roots)).size));
    await expect(metric('已记录客户端')).toHaveText(String(new Set(snapshot.board!.flatMap(item => item.contributors.map(source => source.cli).filter(Boolean))).size));
    for (const width of [1920, 1280, 390]) {
      await page.setViewportSize({ width, height: width === 390 ? 844 : width === 1280 ? 720 : 1080 });
      await expect(board.getByRole('button', { name: '同步最近改动', exact: true })).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      const firstCard = await board.getByRole('button', { name: /^查看项目 / }).first().boundingBox();
      console.log(JSON.stringify({ viewport: width, first_project: firstCard, viewport_height: page.viewportSize()?.height }));
      expect(firstCard).not.toBeNull();
      if (width >= 1280) expect(firstCard!.y + 80).toBeLessThan(page.viewportSize()!.height);
      await page.screenshot({ path: testInfo.outputPath(`actual-board-${width}.png`), fullPage: false, animations: 'disabled' });
    }
    if (process.env.ASTROCYTE_BOARD_PREVIEW_ONLY === '1') return;
    for (const layout of ['平铺', '按平台', '按分组', '时间线']) {
      await board.getByRole('button', { name: layout, exact: true }).click();
      await expect(board.getByRole('button', { name: /^查看项目 / })).toHaveCount(active.length);
    }
    await board.getByRole('button', { name: '平铺', exact: true }).click();
    const selected = active.find(item => item.name === 'Astrocyte') ?? active[0];
    expect(selected).toBeTruthy();
    const notes = '下一步：复核项目来源并记录待答问题';
    const review = '本轮复盘：活动与完成意愿分开，未扩大权限';
    const group = '当前研究';
    const grantsBefore = server.query('SELECT COUNT(*) AS count FROM local_agent_grants');
    const projectsBefore = server.query('SELECT data FROM local_agent_projects ORDER BY id');
    const jobsBefore = server.query('SELECT COUNT(*) AS count FROM attention_jobs');
    const card = board.locator(`button[data-project-id="${selected.id}"]`);
    await card.focus();
    await page.keyboard.press('Enter');
    const dialog = page.getByRole('dialog', { name: `项目 · ${selected.name}`, exact: true });
    await expect(dialog).toBeVisible();
    await expect(dialog.getByText('未知；没有已批准的进度依据，不从活动时间推断。', { exact: true })).toBeVisible();
    await dialog.getByLabel('备注 / 下一步', { exact: true }).fill(notes);
    await dialog.getByLabel('复盘', { exact: true }).fill(review);
    await dialog.getByLabel('项目分组名称', { exact: true }).fill(group);
    await dialog.getByLabel('我对项目的继续意愿', { exact: true }).fill('想继续做');
    const saveResponse = page.waitForResponse(response => response.url().endsWith(`/registered/${selected.id}/metadata`) && response.request().method() === 'PUT');
    await dialog.getByRole('button', { name: '保存项目记录', exact: true }).click();
    expect((await saveResponse).status()).toBe(200);
    await expect(dialog.getByRole('status').filter({ hasText: '已保存项目记录' })).toBeVisible();
    const saved = (await read()).board!.find(item => item.id === selected.id)!;
    expect(saved.human).toMatchObject({ notes, review, group, intent: '想继续做', archived: false, revision: selected.human.revision + 1 });
    const raw = server.query('SELECT data,revision FROM local_project_metadata WHERE project_id=?', selected.id);
    expect(raw).toHaveLength(1);
    expect(JSON.parse(String(raw[0].data))).toEqual(saved.human);
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await expect(card).toBeFocused();
    await board.locator('summary').filter({ hasText: /^更多筛选/ }).click();
    await board.getByLabel('分组', { exact: true }).selectOption(group);
    await board.getByLabel('继续意愿', { exact: true }).selectOption('想继续做');
    await board.getByLabel('搜索项目', { exact: true }).fill('复核项目来源');
    const headerSearch = page.getByRole('textbox', { name: '搜索已加载项目、目录与备注', exact: true });
    await expect(headerSearch).toHaveAttribute('placeholder', '搜索项目、目录或备注…');
    await headerSearch.fill(selected.name);
    await expect(card).toHaveCount(1);
    await board.getByRole('button', { name: '清除筛选', exact: true }).click();
    await expect(headerSearch).toHaveValue('');
    await expect(board.getByLabel('搜索项目', { exact: true })).toHaveValue('');
    await card.click();
    await dialog.getByRole('checkbox', { name: '归档此项目（可取消并保存恢复）', exact: true }).check();
    const archiveResponse = page.waitForResponse(response => response.url().endsWith(`/registered/${selected.id}/metadata`) && response.request().method() === 'PUT');
    await dialog.getByRole('button', { name: '保存项目记录', exact: true }).click();
    expect((await archiveResponse).status()).toBe(200);
    await expect(dialog.getByRole('status').filter({ hasText: '已保存项目记录' })).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(card).toHaveCount(0);
    await board.getByLabel('归档', { exact: true }).selectOption('archived');
    await expect(card).toHaveCount(1);
    const archived = (await read()).board!.find(item => item.id === selected.id)!;
    expect(archived.human).toMatchObject({ notes, review, group, intent: '想继续做', archived: true, revision: saved.human.revision + 1 });
    const refreshResponse = page.waitForResponse(response => response.url().endsWith('/registered/refresh') && response.request().method() === 'POST', { timeout: 140_000 });
    await board.getByRole('button', { name: '同步最近改动', exact: true }).click();
    expect((await refreshResponse).status()).toBe(200);
    expect((await read()).board!.find(item => item.id === selected.id)!.human).toEqual(archived.human);
    const archivedRaw = server.query('SELECT data,revision FROM local_project_metadata WHERE project_id=?', selected.id);
    await server.restart();
    api = await humanAPI(server.apiURL);
    expect((await read()).board!.find(item => item.id === selected.id)!.human).toEqual(archived.human);
    expect(server.query('SELECT data,revision FROM local_project_metadata WHERE project_id=?', selected.id)).toEqual(archivedRaw);
    await page.reload();
    await expect(board.getByLabel('项目统计')).toBeVisible();
    await board.locator('summary').filter({ hasText: /^更多筛选/ }).click();
    await board.getByLabel('归档', { exact: true }).selectOption('archived');
    await card.click();
    await expect(dialog.getByLabel('备注 / 下一步', { exact: true })).toHaveValue(notes);
    await expect(dialog.getByLabel('复盘', { exact: true })).toHaveValue(review);
    await dialog.getByRole('checkbox', { name: '归档此项目（可取消并保存恢复）', exact: true }).uncheck();
    const restoreResponse = page.waitForResponse(response => response.url().endsWith(`/registered/${selected.id}/metadata`) && response.request().method() === 'PUT');
    await dialog.getByRole('button', { name: '保存项目记录', exact: true }).click();
    expect((await restoreResponse).status()).toBe(200);
    await expect(dialog.getByRole('status').filter({ hasText: '已保存项目记录' })).toBeVisible();
    for (const width of [390, 1280, 1920]) {
      await page.setViewportSize({ width, height: width === 390 ? 844 : width === 1280 ? 720 : 1080 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
      await page.screenshot({ path: testInfo.outputPath(`actual-project-detail-${width}.png`), fullPage: true, animations: 'disabled' });
    }
    await page.keyboard.press('Escape');
    await board.getByLabel('归档', { exact: true }).selectOption('active');
    await expect(card).toHaveCount(1);
    expect(server.query('SELECT COUNT(*) AS count FROM local_agent_grants')).toEqual(grantsBefore);
    expect(server.query('SELECT data FROM local_agent_projects ORDER BY id')).toEqual(projectsBefore);
    expect(server.query('SELECT COUNT(*) AS count FROM attention_jobs')).toEqual(jobsBefore);
    expect(errors).toEqual([]);
    await writeFile(testInfo.outputPath('actual-after-restart.json'), JSON.stringify(await read(), null, 2));
  } catch (error) { primaryError = error; throw error; }
  finally { await server.close({ preserveData: true, primaryError }); }
});
