import { test, expect } from '@playwright/test';
import { startS1Server } from '../../tests/s1/server.mjs';
import { humanAPI, waitJob } from '../../tests/s1/api.mjs';
import { importMaterial } from '../../tests/s1/api.mjs';
import { changedPaperText, paperImport, paperText, videoImport, videoTranscript } from '../../tests/s1/fixtures.mjs';
import { seedCandidate } from '../../tests/s1/scenarios.mjs';

// Each viewport owns its own API/Vite/data directory. Existing S0 tests stay empty.
// Synthetic contract_local inputs use real HTTP/SQLite/objects; no page.route mocks.
test.describe('S1 contract_local with real API and persistence', () => {
  let server: Awaited<ReturnType<typeof startS1Server>>;
  let api: Awaited<ReturnType<typeof humanAPI>>;
  test.beforeAll(async () => {
    test.setTimeout(120_000);
    server = await startS1Server({ browser: true });
    api = await humanAPI(server.apiURL);
  });
  test.afterAll(async () => { if (server) await server.close(); });

  test('fresh browser bootstraps a human session and settles actual empty collections', async ({ page }) => {
    const materialsResponse = page.waitForResponse(response => response.url() === `${server.webURL}/api/v1/materials`);
    await page.goto(`${server.webURL}/attention`);
    expect((await materialsResponse).status()).toBe(200);
    await expect(page.getByRole('heading', { name: '资料沉淀', exact: true })).toBeVisible();
    await expect(page.getByText('暂无素材', { exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '研究机会', exact: true }).click();
    await expect(page.getByText('暂无机会', { exact: true })).toBeVisible();
    await expect(page.getByRole('alert').filter({ hasText: '示例数据模式' })).toHaveCount(0);
    expect((await api.get('/materials')).items).toHaveLength(0);
  });

  test('browser imports a summarize representative export and exposes its retained positions', async ({ page }, testInfo) => {
    const input = videoImport('https://youtu.be/S1LOCAL005a');
    await page.goto(`${server.webURL}/attention`);
    await page.getByRole('main').getByRole('button', { name: '添加资料', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('导入方式', { exact: true }).selectOption('summarize');
    await dialog.getByLabel(/视频原始来源/).fill(input.source_locator);
    await dialog.getByLabel(/summarize 导出内容/).fill(input.export_text);
    const receiptResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/materials/imports') && response.request().method() === 'POST');
    await dialog.getByRole('button', { name: '导入资料', exact: true }).click();
    const response = await receiptResponse;
    expect(response.status()).toBe(202);
    const receipt = await response.json();
    const job = await waitJob(api, receipt.job_id);
    const detail = await api.get(`/materials/${job.material_id}`);
    expect(detail.material.collection_reason).toBeNull();
    await dialog.getByRole('button', { name: '关闭', exact: true }).click();
    await page.getByRole('main').getByRole('button', { name: '↻ 刷新', exact: true }).click();
    const card = page.getByRole('button').filter({ has: page.getByText('contract_local 视频代表导出', { exact: true }) });
    await expect(card).toBeVisible();
    await card.focus();
    await page.keyboard.press('Enter');
    await expect(page.getByRole('dialog')).toContainText(videoTranscript);
    await expect(page.getByRole('dialog')).toContainText('0.000s');
    await expect(page.getByRole('dialog').getByRole('link', { name: /summarize.json/ })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('s1-import-source.png'), fullPage: true });
    expect((await api.get('/missions')).items).toHaveLength(0);
  });

  test('view and refresh stay neutral; an explicit keyboard reread increments human attention once', async ({ page }, testInfo) => {
    const input = { ...paperImport('https://example.invalid/contract-local/browser-reread'), title: 'contract_local 浏览器重读材料' };
    const imported = await importMaterial(api, input);
    await importMaterial(api, { ...input, export_text: changedPaperText });
    const id = imported.detail.material.id;
    const baseline = await api.get(`/materials/${id}`);
    const humanCount = baseline.material.human_usage_count;
    if (humanCount === undefined) throw new Error('S1 material omitted its human usage count');
    await page.goto(`${server.webURL}/attention`);
    await page.getByRole('main').getByRole('button', { name: '↻ 刷新', exact: true }).click();
    const card = page.getByRole('button').filter({ has: page.getByText(input.title, { exact: true }) });
    await card.click();
    const dialog = page.getByRole('dialog');
    await expect(dialog.getByLabel('原文版本', { exact: true })).toHaveValue('2');
    await dialog.getByLabel('原文版本', { exact: true }).selectOption('1');
    await expect(dialog.locator('pre').filter({ hasText: paperText })).toHaveText(paperText);
    const detailResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/materials/${id}`));
    await dialog.getByRole('button', { name: '刷新资料详情', exact: true }).click();
    expect((await detailResponse).status()).toBe(200);
    expect((await api.get(`/materials/${id}`)).material.human_usage_count).toBe(baseline.material.human_usage_count);
    const rereadResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/materials/${id}/uses`) && response.request().method() === 'POST');
    const reread = dialog.getByRole('button', { name: '主动重读', exact: true });
    await expect(reread).toBeEnabled();
    await reread.focus();
    await page.keyboard.press('Enter');
    expect((await rereadResponse).status()).toBe(200);
    await expect.poll(async () => (await api.get(`/materials/${id}`)).material.human_usage_count).toBe(humanCount + 1);
    await page.screenshot({ path: testInfo.outputPath('s1-human-reread.png'), fullPage: true });
  });

  test('AT04: later records the displayed candidate revision and survives browser/service reconnection', async ({ page }, testInfo) => {
    const seeded = await seedCandidate(api, 'https://example.invalid/contract-local/browser-later');
    const candidate = seeded.candidate.opportunity;
    if (!candidate.title) throw new Error('S1 candidate omitted its title');
    await page.goto(`${server.webURL}/attention`);
    const card = page.locator('li[role="button"]').filter({ has: page.getByText(candidate.title, { exact: true }) });
    await card.click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('反馈类型', { exact: true }).selectOption('later');
    await dialog.getByLabel(/反馈理由/).fill('contract_local 以后再做；保留资料待真实验证');
    const reviewResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/opportunities/${candidate.id}/reviews`) && response.request().method() === 'POST');
    await dialog.getByRole('button', { name: '保存人工反馈', exact: true }).click();
    expect((await reviewResponse).status()).toBe(201);
    await expect.poll(async () => (await api.get(`/opportunities/${candidate.id}`)).opportunity.state).toBe('deferred');
    const saved = await api.get(`/opportunities/${candidate.id}`);
    expect(saved.reviews).toHaveLength(1);
    expect(saved.reviews[0]).toMatchObject({ revision: candidate.revision, feedback: 'later' });
    expect(saved.reviews.some((review: { feedback: string }) => review.feedback === 'reject')).toBe(false);
    expect((await api.get(`/materials/${seeded.detail.material.id}`)).material.lifecycle).toBe('active');
    await page.screenshot({ path: testInfo.outputPath('s1-later-feedback.png'), fullPage: true });
    await server.restart();
    api = await humanAPI(server.apiURL);
    const reconnectResponse = page.waitForResponse(response => response.url() === `${server.webURL}/api/v1/opportunities`);
    await page.reload();
    expect((await reconnectResponse).status()).toBe(200);
    await card.click();
    await expect(page.getByRole('dialog')).toContainText('contract_local 以后再做；保留资料待真实验证');
    expect(await api.get(`/opportunities/${candidate.id}`)).toEqual(saved);
    expect((await api.get(`/materials/${seeded.detail.material.id}/revisions/1/content`)).text).toBe(paperText);
    expect((await api.get('/missions')).items).toHaveLength(0);
  });

  test('human classification and @ retain the original file and pinned revision; removing the reference keeps the source', async ({ page }, testInfo) => {
    const input = { ...paperImport('https://example.invalid/contract-local/browser-space'), title: 'contract_local 空间原资料' };
    const imported = await importMaterial(api, input);
    const id = imported.detail.material.id;
    await page.goto(`${server.webURL}/attention`);
    const main = page.getByRole('main');
    await main.locator('summary').filter({ hasText: /^管理资料域、排序与空间引用$/ }).click();
    const domainForm = main.locator('details').filter({ hasText: '新建资料域' });
    await domainForm.locator('summary').click();
    await domainForm.getByLabel('域名称', { exact: true }).fill('contract_local 浏览器资料域');
    await domainForm.getByLabel('域说明', { exact: true }).fill('人工纳入；原文仍保留');
    const domainResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/material-domains') && response.request().method() === 'POST');
    await domainForm.getByRole('button', { name: '创建资料域', exact: true }).click();
    const createdDomain = await domainResponse;
    expect(createdDomain.status()).toBe(201);
    const domainID = (await createdDomain.json()).domain.id;
    const materialCard = main.getByRole('button').filter({ has: page.getByText(input.title, { exact: true }) });
    await materialCard.click();
    const dialog = page.getByRole('dialog');
    await dialog.getByRole('checkbox', { name: 'contract_local 浏览器资料域', exact: true }).check();
    const classifyResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/materials/${id}/domains`) && response.request().method() === 'PUT');
    await dialog.getByRole('button', { name: '保存人工分类', exact: true }).click();
    expect((await classifyResponse).status()).toBe(200);
    await expect.poll(async () => (await api.get(`/materials/${id}`)).material.domain_ids).toEqual([domainID]);
    await dialog.getByRole('button', { name: '关闭', exact: true }).click();
    const spaceForm = main.locator('details').filter({ hasText: '创建项目顶层空间' });
    await spaceForm.locator('summary').click();
    await spaceForm.getByLabel('空间名称', { exact: true }).fill('contract_local 浏览器空间');
    const spaceResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/project-spaces') && response.request().method() === 'POST');
    await spaceForm.getByRole('button', { name: '创建空间', exact: true }).click();
    const createdSpace = await spaceResponse;
    expect(createdSpace.status()).toBe(201);
    const spaceID = (await createdSpace.json()).space.id;
    const references = main.locator('section[aria-label="空间资料引用"]');
    await references.getByLabel('@ 资料', { exact: true }).selectOption(id);
    await references.getByLabel('@ 固定内容版本', { exact: true }).selectOption('1');
    const referenceResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/project-spaces/${spaceID}/references`) && response.request().method() === 'POST');
    await references.getByRole('button', { name: '@ 引用文件', exact: true }).click();
    expect((await referenceResponse).status()).toBe(200);
    await expect.poll(async () => (await api.get(`/project-spaces/${spaceID}`)).space.material_refs.length).toBe(1);
    await importMaterial(api, { ...input, export_text: changedPaperText });
    await main.getByRole('button', { name: '↻ 刷新', exact: true }).click();
    await main.getByLabel('资料域筛选', { exact: true }).selectOption(domainID);
    await expect(materialCard).toBeVisible();
    await materialCard.click();
    await expect(dialog.getByLabel('原文版本', { exact: true })).toHaveValue('2');
    await expect(dialog.getByRole('checkbox', { name: 'contract_local 浏览器资料域', exact: true })).toBeChecked();
    await dialog.getByLabel('原文版本', { exact: true }).selectOption('1');
    await expect(dialog.locator('pre').filter({ hasText: paperText })).toHaveText(paperText);
    await dialog.getByRole('button', { name: '关闭', exact: true }).click();
    expect((await api.get(`/project-spaces/${spaceID}`)).space.material_refs[0]).toMatchObject({ material_id: id, revision: 1 });
    const removeResponse = page.waitForResponse(response => response.url().endsWith(`/api/v1/project-spaces/${spaceID}/references/remove`) && response.request().method() === 'POST');
    await references.getByRole('button', { name: `移除引用 · ${input.title}`, exact: true }).click();
    expect((await removeResponse).status()).toBe(200);
    await expect.poll(async () => (await api.get(`/project-spaces/${spaceID}`)).space.material_refs).toEqual([]);
    await page.reload();
    await main.locator('summary').filter({ hasText: /^管理资料域、排序与空间引用$/ }).click();
    await main.getByLabel('当前项目顶层空间', { exact: true }).selectOption(spaceID);
    await expect(references.getByRole('button', { name: /^移除引用/ })).toHaveCount(0);
    expect((await api.get(`/materials/${id}`)).material.domain_ids).toEqual([domainID]);
    expect((await api.get(`/materials/${id}/revisions/1/content`)).text).toBe(paperText);
    expect((await api.get('/missions')).items).toHaveLength(0);
    await page.screenshot({ path: testInfo.outputPath('s1-human-space-reference.png'), fullPage: true });
  });

  test('human ranking settings begin empty, preserve versions and survive reload without inventing unknown scores', async ({ page }, testInfo) => {
    await page.goto(`${server.webURL}/attention`);
    const main = page.getByRole('main');
    await main.locator('summary').filter({ hasText: /^管理资料域、排序与空间引用$/ }).click();
    await expect(main.getByText('尚未配置综合排序，权重留空', { exact: true })).toBeVisible();
    const fields = [['目标进展权重', '4'], ['当前兴趣权重', '3'], ['项目改善权重', '2'], ['创新性权重', '1']] as const;
    for (const [label, value] of fields) {
      await expect(main.getByLabel(label, { exact: true })).toHaveValue('');
      await main.getByLabel(label, { exact: true }).fill(value);
    }
    await main.getByRole('checkbox', { name: '启用综合排序', exact: true }).check();
    const firstResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/attention-ranking-profile') && response.request().method() === 'PUT');
    await main.getByRole('button', { name: '保存排序配置', exact: true }).click();
    expect((await firstResponse).status()).toBe(200);
    await expect.poll(async () => (await api.get('/attention-ranking-profile')).profile?.version).toBe(1);
    for (const candidate of (await api.get('/opportunities')).items) expect(candidate.composite_score == null).toBe(true);
    await expect(main.getByText('已保存配置 v1 · 启用', { exact: true })).toBeVisible();
    await main.getByRole('checkbox', { name: '启用综合排序', exact: true }).uncheck();
    const secondResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/attention-ranking-profile') && response.request().method() === 'PUT');
    await main.getByRole('button', { name: '保存排序配置', exact: true }).click();
    expect((await secondResponse).status()).toBe(200);
    const saved = await api.get('/attention-ranking-profile');
    expect(saved.profile?.version).toBe(2);
    expect(saved.profile?.enabled).toBe(false);
    expect(saved.versions.map(profile => profile.version)).toEqual([1, 2]);
    expect(saved.versions[0].enabled).toBe(true);
    await page.reload();
    await main.locator('summary').filter({ hasText: /^管理资料域、排序与空间引用$/ }).click();
    await expect(main.getByText('已保存配置 v2 · 停用', { exact: true })).toBeVisible();
    await expect(main.getByRole('checkbox', { name: '启用综合排序', exact: true })).not.toBeChecked();
    for (const [label, value] of fields) await expect(main.getByLabel(label, { exact: true })).toHaveValue(value);
    const history = main.locator('details').filter({ hasText: '排序配置版本历史' });
    await history.locator('summary').click();
    await expect(history).toContainText('v1 · 启用');
    await expect(history).toContainText('v2 · 停用');
    expect(await api.get('/attention-ranking-profile')).toEqual(saved);
    expect((await api.get('/missions')).items).toHaveLength(0);
    await page.screenshot({ path: testInfo.outputPath('s1-human-ranking-profile.png'), fullPage: true });
  });

  test('default automatic processing remains disabled and opening its form never submits a model job', async ({ page }) => {
    const input = { ...paperImport('https://example.invalid/contract-local/browser-disabled'), title: 'contract_local 未授权自动处理资料' };
    const imported = await importMaterial(api, input);
    const jobsBefore = server.query('SELECT COUNT(*) AS n FROM attention_jobs WHERE json_extract(data,\'$.kind\')=?', 'distillation')[0].n;
    let automaticSubmissions = 0;
    page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/v1/distillations/jobs')) automaticSubmissions++; });
    await page.goto(`${server.webURL}/attention`);
    await page.getByRole('main').getByRole('button').filter({ has: page.getByText(input.title, { exact: true }) }).click();
    const dialog = page.getByRole('dialog');
    const statusResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/distillations/processor'));
    await dialog.getByRole('button', { name: '继续沉淀', exact: true }).click();
    expect((await statusResponse).status()).toBe(200);
    const automatic = dialog.locator('section[aria-label="自动沉淀"]');
    await expect(automatic).toContainText('请先选择已许可的项目与客户端；提交时服务会核对实际配置和本次固定版本范围。');
    await expect(automatic).toContainText('模型 未知 · 配置 未提供');
    await expect(automatic.getByLabel('自动沉淀的项目模型许可', { exact: true })).toHaveValue('');
    await expect(automatic.getByRole('option', { name: '选择已许可项目…', exact: true })).toHaveCount(1);
    await expect(automatic.getByRole('button', { name: '提交自动沉淀', exact: true })).toBeDisabled();
    await expect(automatic.getByLabel('自动沉淀本轮问题', { exact: true })).toBeDisabled();
    const status = await api.get('/distillations/processor');
    expect(status).toMatchObject({ available: false, processor: 'selected-project-cli', configuration_id: null, model: null, required_action: 'select_permitted_project_cli', allowed_source_keys: [] });
    expect(automaticSubmissions).toBe(0);
    expect(server.query('SELECT COUNT(*) AS n FROM attention_jobs WHERE json_extract(data,\'$.kind\')=?', 'distillation')[0].n).toBe(jobsBefore);
    expect((await api.get(`/materials/${imported.detail.material.id}`)).material.human_usage_count).toBe(0);
  });
});
